language: node_js
node_js:
    - 8
addons:
    firefox: "latest"
    chrome: "stable"
install:
    - npm install
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
script:
    - npm run-script dist
    - npm run-script lint
    - npm test
