name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:    
    - name: SCM Checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false

    - name: Build
      run: |
        npm ci
        npm run dist

    - name: Publish
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
       
